# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration


[changelog]
header = """
# Changelog

"""
# A Tera template to be rendered for each release in the changelog.
# See https://keats.github.io/tera/docs/#introduction
body = """
{% macro commit(commit) -%}
{% if commit.scope %}**({{commit.scope}})** {% endif -%}
{% if commit.breaking %}**breaking** {% endif -%}
{{ commit.message | split(pat="\n") | first | trim }} (
{%- if commit.remote.pr_number %}[#{{ commit.remote.pr_number }}]($REPO/pull/{{ commit.remote.pr_number }})
{%- else %}[{{ commit.id | truncate(length=7, end="") }}]($REPO/commit/{{ commit.id }}))
{%- endif %}
{% endmacro commit -%}

{% if version -%}
    {%- if previous.version -%}
        ## [{{ version | trim_start_matches(pat="v") }}]($REPO/compare/{{previous.version}}..{{version}}) - {{ timestamp | date(format="%Y-%m-%d") }}
    {%- else -%}
        ## [{{ version | trim_start_matches(pat="v") }}]($REPO/tree/{{version}}) - {{ timestamp | date(format="%Y-%m-%d") }}
    {%- endif -%}
{%- else -%}
    ## unreleased
{%- endif %}
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}

    {% for commit in commits | filter(attribute="scope") | sort(attribute="scope") -%}
      {% if commit.scope -%}
        - {{ self::commit(commit=commit) }}
      {%- endif -%}
    {% endfor -%}
    {% for commit in commits -%}
      {% if not commit.scope -%}
        - {{ self::commit(commit=commit) }}
      {%- endif -%}
    {% endfor -%}
{% endfor %}

"""
# Remove leading and trailing whitespaces from the changelog's body.
trim = true
# Render body even when there are no releases to process.
render_always = true
# An array of regex based postprocessors to modify the changelog.
postprocessors = [
    { pattern = '\$REPO', replace = "https://github.com/bryanforbes/asyncpg-stubs" },
    # Replace the placeholder <REPO> with a URL.
    #{ pattern = '<REPO>', replace = "https://github.com/orhun/git-cliff" },
]
# render body even when there are no releases to process
# render_always = true
# output file path
# output = "test.md"

[git]
# Parse commits according to the conventional commits specification.
# See https://www.conventionalcommits.org
conventional_commits = true
# Exclude commits that do not match the conventional commits specification.
filter_unconventional = false
# Require all commits to be conventional.
# Takes precedence over filter_unconventional.
require_conventional = false
# Split commits on newlines, treating each line as an individual commit.
split_commits = false
# An array of regex based parsers to modify commit messages prior to further processing.
commit_preprocessors = [
    # remove PR labels from commits
    { pattern = '\s+\(#([0-9]+)\)', replace = "" },
    # Replace issue numbers with link templates to be updated in `changelog.postprocessors`.
    #{ pattern = '\((\w+\s)?#([0-9]+)\)', replace = "([#${2}](<REPO>/issues/${2}))"},
    # Check spelling of the commit message using https://github.com/crate-ci/typos.
    # If the spelling is incorrect, it will be fixed automatically.
    #{ pattern = '.*', replace_command = 'typos --write-changes -' },
]
# Prevent commits that are breaking from being excluded by commit parsers.
protect_breaking_commits = false
# An array of regex based parsers for extracting data from the commit message.
# Assigns commits to groups.
# Optionally sets the commit's scope and can decide to exclude commits from further processing.
commit_parsers = [
    # asyncpg version updates (major/minor) are releasable
    { message = '^chore\(deps\): update dependency asyncpg', group = "<!-- 98 -->Dependency Updates" },
    { body = ".*security", group = "<!-- 08 -->Security" },
    # skip all other chore commits
    { message = '^chore', skip = true },

    { message = '^release:', skip = true },
    { message = '^Release \d+', skip = true },
    { message = '^Post release version bump', skip = true },
    { message = '^ci', skip = true },
    { message = '[lL]ock ?[fF]ile', skip = true },
    { message = "^feat", group = "<!-- 01 -->Features" },
    { message = "^fix", group = "<!-- 02 -->Bug Fixes" },
    { message = "^refactor", group = "<!-- 03 -->Refactor" },
    { message = "^docs", group = "<!-- 04 -->Documentation" },
    { message = "^perf", group = "<!-- 05 -->Performance" },
    { message = "^style", group = "<!-- 06 -->Styling" },
    { message = "^test", group = "<!-- 07 -->Testing" },
    { message = "^[Rr]evert", group = "<!-- 09 -->Revert" },
    { message = '.*', group = "<!-- 99 -->Miscellaneous" },
]
# Exclude commits that are not matched by any commit parser.
filter_commits = false
# An array of link parsers for extracting external references, and turning them into URLs, using regex.
link_parsers = []
# Include only the tags that belong to the current branch.
use_branch_tags = false
# Order releases topologically instead of chronologically.
topo_order = false
# Order releases topologically instead of chronologically.
topo_order_commits = true
# Order of commits in each group/release within the changelog.
# Allowed values: newest, oldest
sort_commits = "oldest"
# Process submodules commits
recurse_submodules = false
